SQL> select s.phone_number, s.student_name,
  2     a.address_id, a.country, a.province, a.city, a.street, a.house_number, a.fax_number
  3      from student s
  4      join student_details sd
  5      on s.phone_number=sd.phone_number
  6      join address_Details ad
  7      on sd.student_id=ad.student_id
  8      join address a
  9      on ad.address_id=a.address_id;

PHONE_NUMBER STUDENT_NAME              ADDRESS_ID COUNTRY                        PROVINCE                       CITY                          STREET HOUSE_NUMBER FAX_NUMBER                                                                                                                                                                                                                                                                                                                                        
------------ ------------------------- ---------- ------------------------------ ------------------------------ ------------------------- ---------- ------------ ----------                                                                                                                                                                                                                                                                                                                                        
  9843117125 Shyam Nepal                     1001 Nepal                          one                            kathmandu                       2467          101       6247                                                                                                                                                                                                                                                                                                                                        
  9843256794 Raj Nepal                       1002 Nepal                          Two                            phokara                         3569          102       2456                                                                                                                                                                                                                                                                                                                                        
  9860807352 krishna Nepal                   1003 Nepal                          Three                          Bharatpur                       4894          103       8645                                                                                                                                                                                                                                                                                                                                        
  9846547526 Hari Poudel                     1004 Nepal                          Four                           Butwal                          8996          104       4679                                                                                                                                                                                                                                                                                                                                        
  9860919090 Ashok Nepal                     1005 Nepal                          Five                           Ithari                          5432          105       1509                                                                                                                                                                                                                                                                                                                                        
  9845679443 Santosh Gajurel                 1006 Nepal                          Six                            Trishuli                        6432          106       3567                                                                                                                                                                                                                                                                                                                                        
  9813279191 Sandip Gajurel                  1007 Nepal                          Seven                          Dhamak                          7794          107       7458                                                                                                                                                                                                                                                                                                                                        

7 rows selected.

SQL> spool off;
