SQL>  select course_leader,phone_number from course
  2     join course_details
  3      using(course_name)
  4      join teacher_details
  5      using(course_id);

COURSE_LEADER                  PHONE_NUMBER                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
------------------------------ ------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Biwash Adhikari                  9843217325                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Upesh nepal                      9860657126                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Raj Manander                     9845278573                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Prashant Nepal                   9840442375                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Santosh Pendey                   9846677694                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Prashant Nepal                   9850555775                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Raj Manander                     9860616668                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

7 rows selected.

SQL> spoool off;
SP2-0042: unknown command "spoool off" - rest of line ignored.
SQL> spool off;
