SQL> select course_name, course_leader
  2  from course
  3  join course_details
  4  using(course_name)
  5  join teacher_details
  6  using(course_id);

COURSE_NAME                    COURSE_LEADER                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
------------------------------ ------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                       
BSCIT                          Biwash Adhikari                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
BBA                            Upendra Poudel                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
BBS                            Bikram Lamichhane                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
BIM                            Ishwor Pokharel                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
BHM                            Binod Shrestha                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
BIM                            Ishwor Pokharel                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
BBS                            Bikram Lamichhane                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

7 rows selected.

SQL> spool off;
